base:
  config: []
  log:
    format: console
    level: debug
  experimental:
    features: []
credentials-id: client.lorawan.co.ua
input-format: json
output-format: json
allow-unknown-hosts: false
oauth-server-address: http://client.lorawan.co.ua:1885/oauth
identity-server-grpc-address: client.lorawan.co.ua:8884
gateway-server-enabled: true
gateway-server-grpc-address: client.lorawan.co.ua:8884
network-server-enabled: true
network-server-grpc-address: client.lorawan.co.ua:8884
application-server-enabled: true
application-server-grpc-address: client.lorawan.co.ua:8884
join-server-enabled: true
join-server-grpc-address: client.lorawan.co.ua:8884
device-template-converter-grpc-address: client.lorawan.co.ua:8884
device-claiming-server-grpc-address: client.lorawan.co.ua:8884
qr-code-generator-grpc-address: client.lorawan.co.ua:8884
packet-broker-agent-grpc-address: client.lorawan.co.ua:8884
insecure: false
ca: "./ca.pem"
dump-requests: false
skip-version-check: false

