# Identity Server configuration
# Email configuration for "client.lorawan.co.ua"
is:
  email:
    sender-name: 'The Things Stack'
    sender-address: 'noreply@client.lorawan.co.ua'
    network:
      name: 'The Things Stack'
      console-url: 'http://client.lorawan.co.ua:1885/console'
      identity-server-url: 'http://client.lorawan.co.ua:1885/oauth'

    # If sending email with Sendgrid
    # provider: sendgrid
    # sendgrid:
    #   api-key: '...'              # enter Sendgrid API key

    # If sending email with SMTP
    # provider: smtp
    # smtp:
    #   address:  '...'             # enter SMTP server address
    #   username: '...'             # enter SMTP server username
    #   password: '...'             # enter SMTP server password

# Web UI configuration for "client.lorawan.co.ua":
  oauth:
    ui:
      canonical-url: 'http://client.lorawan.co.ua:1885/oauth'
      is:
        base-url: 'https://client.lorawan.co.ua:8885/api/v3'

# HTTP server configuration
http:
  cookie:
# generate 32 bytes (openssl rand -hex 32)
    block-key: 'b565ec7190d30d43d6551768844929d02d307dfee6b311ee3acf441a9924ba01'
# generate 64 bytes (openssl rand -hex 64)
    hash-key: '170095dc8ad7c230742e5b288f660b184286733d94acb1fa072aafc1a3d177a135d00dd0e626f2a0cc22b3eed5e6fdf33d718133d317a4f3c353e1deee6b93bd'
  metrics:
# choose a password
    password: 'metrics'
  pprof:
# choose a password
    password: 'pprof' 

# If using custom certificates:
tls:
  source: file
  root-ca: /run/secrets/ca.pem
  certificate: /run/secrets/cert.pem
  key: /run/secrets/key.pem

# Let's encrypt for "client.lorawan.co.ua"
#tls:
#  source: 'acme'
#  acme:
#    dir: '/var/lib/acme'
#    email: 'uy0ll@yahoo.com'
#    hosts: ['client.lorawan.co.ua']
#    default-host: 'client.lorawan.co.ua'

# If Gateway Server enabled, defaults for "client.lorawan.co.ua":
gs:
  mqtt:
    public-address: 'client.lorawan.co.ua:1882'
    public-tls-address: 'client.lorawan.co.ua:8882'
  mqtt-v2:
    public-address: 'client.lorawan.co.ua:1881'
    public-tls-address: 'client.lorawan.co.ua:8881'

# If Gateway Configuration Server enabled, defaults for "client.lorawan.co.ua":
gcs:
  basic-station:
    default:
      lns-uri: 'wss://client.lorawan.co.ua:8887'
  the-things-gateway:
    default:
      mqtt-server: 'mqtts://client.lorawan.co.ua:8881'

# Web UI configuration for "client.lorawan.co.ua":
console:
  ui:
    canonical-url: 'https://client.lorawan.co.ua:8885/console'
    is:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'
    gs:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'
    gcs:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'
    ns:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'
    as:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'
    js:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'
    qrg:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'
    edtc:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'

  oauth:
    authorize-url: 'https://client.lorawan.co.ua:8885/oauth/authorize'
    token-url: 'https://client.lorawan.co.ua:8885/oauth/token'
    logout-url: 'https://client.lorawan.co.ua:8885/oauth/logout'
    client-id: 'console'
# choose or generate a secret
    client-secret: 'console'

# If Application Server enabled, defaults for "client.lorawan.co.ua":
as:
  mqtt:
    public-address: 'http://client.lorawan.co.ua:1883'
    public-tls-address: 'https://client.lorawan.co.ua:8883'
  webhooks:
    downlink:
      public-address: 'https://client.lorawan.co.ua:8885/api/v3'

# If Device Claiming Server enabled, defaults for "client.lorawan.co.ua":
dcs:
  oauth:
    authorize-url: 'https://client.lorawan.co.ua:8885/oauth/authorize'
    token-url: 'https://client.lorawan.co.ua:8885/oauth/token'
    logout-url: 'https://client.lorawan.co.ua:8885/oauth/logout'
    client-id: 'device-claiming'
# choose or generate a secret
    client-secret: 'device-claiming'
  ui:
    canonical-url: 'https://client.lorawan.co.ua:8885/claim'
    as:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'
    dcs:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'
    is:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'
    ns:
      base-url: 'https://client.lorawan.co.ua:8885/api/v3'

